# Generated by Django 5.0.3 on 2024-03-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(choices=[('RU', 'Россия'), ('TR', 'Турция'), ('CN', 'Китай')], default=('RU', 'Россия'), max_length=2),
            preserve_default=False,
        ),
    ]
